config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources 'notifications', only: [:create]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :error, :success
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @house = {
      title: '555 Sunnybrook Lane',
      price: '$349,999',
      description: 'You and your family will love this charming home. ' +
      'Featuring granite appliances, stainless steel windows, and ' +
      'high efficiency dual mud rooms, this joint is loaded to the max. ' +
      'Motivated sellers have priced for a quick sale, act now!'
    }
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

require 'message_sender'
class NotificationsController < ApplicationController
  def create
    MessageSender.send_message(message)
    redirect_to root_url,
      success: 'Thanks! An agent will be contacting you shortly.'
  rescue Twilio::REST::TwilioError => error
    p error.message
    redirect_to root_url,
      error: 'Oops! There was an error. Please try again.'
  end

  private

  def message
    "New lead received for #{params[:house_title]}. " \
    "Call #{params[:name]} at #{params[:phone]}. " \
    "Message: #{params[:message]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.haml
.row
  .col-sm-8
    %h1= @house[:title]
    %h3= @house[:price]
    %p= image_pack_tag "house.jpg", class: "img-responsive"
    %p= @house[:description]

  .col-sm-4.demo
    %h4 Talk To An Agent
    %p
      A trained real estate professional is standing by to answer any
      questions you might have about this property. Fill out the form below
      with your contact information, and an agent will reach out soon.

    = form_tag notifications_path do
      %input{type: 'hidden', name: 'house_title', value: @house[:title]}
      .form-group
        %label{for: 'name'} Your Name
        %input.form-control{name: 'name', placeholder: 'John Appleseed'}

      .form-group
        %label{for: 'phone'} Your Phone Number
        %input.form-control{name: 'phone', placeholder: '+16512229988'}

      .form-group
        %label{for: 'message'} How can we help?
        %input.form-control{name: 'message'}

      %button.btn.btn-primary{type: 'submit'} Request Info

app/views/layouts/application.haml
!!!
%html
  %head
    %title
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_pack_tag 'application'
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css'
    = csrf_meta_tags
  %body
    #main.container
      - if success
        .alert.alert-success.alert-dismissible.fade.in{role: 'alert'}
          %button.close{type: 'button', data: { dismiss: 'alert' }, aria: { hidden: 'true'}}
            %span{ aria: { hidden: 'true' }} &times;
          %p= success
      - if error
        .alert.alert-danger.alert-dismissible.fade.in{role: 'alert'}
          %button.close{type: 'button', data: { dismiss: 'alert' }, aria: { hidden: 'true'}}
            %span{ aria: { hidden: 'true' }} &times;
          %p= error
      = yield

    %footer.container
      Made with <i class="fa fa-heart"></i> by your pals <a href="http://www.twilio.com">@twilio</a>.